import 'src/styles/globals.css';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
	<Head>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
	</Head>;
	return <Component {...pageProps} />;
}

export default MyApp;
