import Head from 'next/head';
import Image from 'next/image';
import { Footer } from '../components/footer';
import styles from '../styles/Home.module.css';
import { Main } from '../components/main';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>about page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Main page="about" />
			<Footer />
		</div>
	);
}
